def build(bld):
  bld(features     ='cxx cprogram',
      source       = 'performanceTest.cpp',
      target       = 'performance_test',
      install_path  = None,
      includes     = '.',
      uselib_local = 'redsvd')
  bld(features     ='cxx cprogram',
      source       = 'accuracyTest.cpp',
      target       = 'accuracy_test',
      install_path  = None,
      includes     = '.',
      uselib_local = 'redsvd')
  bld(features     ='cxx cprogram',
      source       = 'mmio.cpp countc.cpp',
      target       = 'count',
      install_path  = None,
      includes     = '.',
      uselib_local = 'redsvd')

